/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.clinica.medica;

/**
 *
 * @author 232-001135
 */
public class TelaRegistro extends javax.swing.JFrame {

    /**
     * Creates new form Teste
     */
    public TelaRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenu = new javax.swing.JMenuBar();
        inicio = new javax.swing.JMenu();
        consulta = new javax.swing.JMenu();
        agendarConsulta = new javax.swing.JMenuItem();
        pesquisarConsulta = new javax.swing.JMenuItem();
        reagendarConsulta = new javax.swing.JMenuItem();
        cancelarConsulta = new javax.swing.JMenuItem();
        pacientes = new javax.swing.JMenu();
        medicos = new javax.swing.JMenu();
        usuarios = new javax.swing.JMenu();
        cadastrarUsuario = new javax.swing.JMenuItem();
        consultarUsuario = new javax.swing.JMenuItem();
        alterarUsuario = new javax.swing.JMenuItem();
        excluirUsuario = new javax.swing.JMenuItem();
        opcoes = new javax.swing.JMenu();
        sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inicio.setText("Início");
        barraMenu.add(inicio);

        consulta.setText("Consultas");

        agendarConsulta.setText("Agendar");
        consulta.add(agendarConsulta);

        pesquisarConsulta.setText("Pesquisar");
        pesquisarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarConsultaActionPerformed(evt);
            }
        });
        consulta.add(pesquisarConsulta);

        reagendarConsulta.setText("Reagendar");
        consulta.add(reagendarConsulta);

        cancelarConsulta.setText("Cancelar");
        consulta.add(cancelarConsulta);

        barraMenu.add(consulta);

        pacientes.setText("Pacientes");
        barraMenu.add(pacientes);

        medicos.setText("Médicos");
        barraMenu.add(medicos);

        usuarios.setText("Usuários");

        cadastrarUsuario.setText("Cadastrar");
        cadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarUsuarioActionPerformed(evt);
            }
        });
        usuarios.add(cadastrarUsuario);

        consultarUsuario.setText("Consultar");
        usuarios.add(consultarUsuario);

        alterarUsuario.setText("Alterar");
        alterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarUsuarioActionPerformed(evt);
            }
        });
        usuarios.add(alterarUsuario);

        excluirUsuario.setText("Excluir");
        usuarios.add(excluirUsuario);

        barraMenu.add(usuarios);

        opcoes.setText("Opções");
        barraMenu.add(opcoes);

        sair.setText("Sair");
        barraMenu.add(sair);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void alterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alterarUsuarioActionPerformed

    private void cadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarUsuarioActionPerformed

    private void pesquisarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem agendarConsulta;
    private javax.swing.JMenuItem alterarUsuario;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem cadastrarUsuario;
    private javax.swing.JMenuItem cancelarConsulta;
    private javax.swing.JMenu consulta;
    private javax.swing.JMenuItem consultarUsuario;
    private javax.swing.JMenuItem excluirUsuario;
    private javax.swing.JMenu inicio;
    private javax.swing.JMenu medicos;
    private javax.swing.JMenu opcoes;
    private javax.swing.JMenu pacientes;
    private javax.swing.JMenuItem pesquisarConsulta;
    private javax.swing.JMenuItem reagendarConsulta;
    private javax.swing.JMenu sair;
    private javax.swing.JMenu usuarios;
    // End of variables declaration//GEN-END:variables
}
